name: CI

on: [push]

jobs:
  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [4.02.0, 4.09.0]

    steps:
    - uses: actions/checkout@v1
    - name: Setup opam and ocaml
      uses: fangyi-zhou/actions-ocaml@v1
      with:
        ocaml_version: ${{ matrix.ocaml }}
    - name: Install num
      if: startsWith(matrix.ocaml, '4.09')
      run: opam install -y num
    - name: Download and build gelpia
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        git clone https://github.com/soarlab/gelpia.git
        cd gelpia
        git checkout version_2
        make requirements
        make
    - name: Build FPTaylor
      run: make
    - name: Run basic tests
      run: |
        grep opt -C 3 default.cfg
        make test
    - name: Run basic tests with gelpia
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sed -i "s|^opt = bb|opt = gelpia|g" default.cfg
        make test
