name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ocaml
      run: sudo apt install ocaml
    - name: Build FPTaylor
      run: make
    - name: Run basic tests
      run: make test
